### ISSUE TITLE
Lots of errors during compile on Arduino

### ISSUE THREAD

**Issue by masterprompt** [hideakitai/Tween#9]
Just using the starting example:

```
test.ino In member function 'typename arx::stdx::enable_if<arx::stdx::is_convertible<U, T>::value, ht::tween::sequence::Sequence<T>&>::type ht::tween::sequence::Sequence<T>::then(const U&, double, const TransitionCallback&) [with EasingType = ht::ease::LinearInOut; U = int; T = float; typename arx::stdx::enable_if<arx::stdx::is_convertible<U, T>::value, ht::tween::sequence::Sequence<T>&>::type = ht::tween::sequence::Sequence<float>&; ht::tween::TransitionCallback = arx::stdx::function<void()>]':
test.ino  :34:23: error: could not convert 'nullptr' from 'std::nullptr_t' to 'const TransitionCallback& {aka const arx::stdx::function<void()>&}'
         .then(10, 5000)  // to 10 in 5000[ms]
```

Also, is this library no longer updated?  Haven't seen any movement on it in some time...

**Comment by lipsumar** [comment]
Please bear in mind that i'm an absolute noob in C++, but it seems the "Simple Usage" example doesn't work because of the "callback feature". It seems like `then()` and `hold()` (possibly others too) now requires a callback as a last argument. Here's code that works for me:

```c++
timeline.add(tweenTarget)    // target tweens
  .init(0)                   // init target value (optional)
  .then(255, 1000, []() {})  // to 255 in 1000[ms]
  .hold(1000, []() {})       // then stops 1000[ms]
  .then(0, 1000, []() {});   // then to 0 in 1000[ms]
```

Notice the empty callback `[]() {}` as a last argument to `then` and `hold`. 

Again, I'm not quite sure what I'm doing, I base this answer on the example found [here](https://github.com/hideakitai/Tween/blob/0.3.9/examples/transition_callback/transition_callback.ino). I think this is the related PR: https://github.com/hideakitai/Tween/pull/6 

@hideakitai could this be a simple case of an incorrect default for the callback function ?

**Comment by hideakitai** [comment]
Hi, which board are you using? Please let me know with a board version. In my environment, esp32 v2.0.11 works well.

**Comment by lipsumar** [comment]
I'm using an Arduino Uno, compiling in the Arduino IDE 2.1.0. The error I get is exactly the same as described above

**Comment by hideakitai** [comment]
Fixed by https://github.com/hideakitai/Tween/pull/11
